//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeMaster.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblEmployeeMaster
    {
        public int EmployeeId { get; set; }
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Please enter first name")]
        public string First_Name { get; set; }
        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Please enter last name")]
        public string Last_Name { get; set; }
        [Range(16, 100, ErrorMessage = "Age must be between 16 - 100")]
        public Nullable<int> Age { get; set; }
        [Display(Name = "Salary")]
        [RegularExpression(@"[0-9]+(\.[0-9]+)?", ErrorMessage = "Please enter valid salary detail.")]
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> DepartmentID { get; set; }

        public virtual tblDepartment tblDepartment { get; set; }
    }
}
